"""Daily summary — structured 'what did YETI do today' drawer.

Not a push channel. Writes one drawer per day in wing=meta,
room=daily-summary so future-Claude (and Daniel) can query the
trajectory of a project / week / month via the standard memory_search
path. Built on top of stores already in place (notes, inbox, audit,
superseded). No LLM cost.
"""

import json
import logging
import sqlite3
from datetime import UTC, datetime, timedelta
from pathlib import Path

from yeti.config import settings

logger = logging.getLogger(__name__)
DB_PATH = Path(settings.db_path)


def _conn() -> sqlite3.Connection:
    conn = sqlite3.connect(str(DB_PATH))
    conn.row_factory = sqlite3.Row
    return conn


def collect_metrics(window_start: datetime) -> dict:
    """Aggregate metrics since `window_start`. Read-only."""
    iso = window_start.isoformat()

    metrics: dict = {
        "since": iso,
        "until": datetime.now(UTC).isoformat(),
    }

    try:
        with _conn() as conn:
            # Notes by triage level
            level_rows = conn.execute(
                """
                SELECT triage_level, COUNT(*) AS n
                FROM notes
                WHERE created_at >= ?
                GROUP BY triage_level
                """,
                (iso,),
            ).fetchall()
            metrics["notes_by_level"] = {
                (r["triage_level"] or "unclassified"): r["n"]
                for r in level_rows
            }

            # Inbox created today
            row = conn.execute(
                "SELECT COUNT(*) AS n FROM inbox "
                "WHERE created_at >= ?",
                (iso,),
            ).fetchone()
            metrics["inbox_created"] = row["n"] if row else 0

            # Inbox resolved today (audit action=resolved)
            row = conn.execute(
                """
                SELECT COUNT(*) AS n FROM inbox_audit
                WHERE action = 'resolved' AND timestamp >= ?
                """,
                (iso,),
            ).fetchone()
            metrics["inbox_resolved"] = row["n"] if row else 0

            # Auto-applied resolutions
            audit_rows = conn.execute(
                """
                SELECT details FROM inbox_audit
                WHERE action = 'resolved' AND timestamp >= ?
                """,
                (iso,),
            ).fetchall()
            auto = 0
            for ar in audit_rows:
                try:
                    d = json.loads(ar["details"] or "{}")
                except json.JSONDecodeError:
                    continue
                if "auto-applied" in (d.get("note") or ""):
                    auto += 1
            metrics["inbox_auto_resolved"] = auto

            # Drawers superseded today
            try:
                row = conn.execute(
                    """
                    SELECT COUNT(*) AS n FROM superseded_drawers
                    WHERE ts >= ?
                    """,
                    (iso,),
                ).fetchone()
                metrics["drawers_superseded"] = (
                    row["n"] if row else 0
                )
            except sqlite3.OperationalError:
                metrics["drawers_superseded"] = 0
    except Exception:
        logger.exception("Daily summary metric collection failed")

    return metrics


def render_summary(date_label: str, metrics: dict) -> str:
    """Render metrics into a drawer body."""
    lines = [f"# Daily Summary — {date_label}"]
    lines.append("")
    lines.append(f"Window: {metrics.get('since')} → {metrics.get('until')}")
    lines.append("")

    notes_by_level = metrics.get("notes_by_level") or {}
    if notes_by_level:
        lines.append("## Triage volume")
        for level in ("full", "informational", "discard", "unclassified"):
            n = notes_by_level.get(level, 0)
            if n:
                lines.append(f"- {level}: {n}")
        lines.append("")

    lines.append("## Inbox activity")
    lines.append(
        f"- created: {metrics.get('inbox_created', 0)}"
    )
    lines.append(
        f"- resolved: {metrics.get('inbox_resolved', 0)}"
    )
    auto = metrics.get("inbox_auto_resolved", 0)
    if auto:
        lines.append(f"- auto-resolved: {auto}")
    lines.append("")

    superseded = metrics.get("drawers_superseded", 0)
    if superseded:
        lines.append("## Memory hygiene")
        lines.append(
            f"- drawers superseded: {superseded}"
        )
        lines.append("")

    lines.append(
        "(Auto-generated by sleep summary. "
        "Search wing=meta room=daily-summary to read the timeline.)"
    )
    return "\n".join(lines)


async def run_daily_summary() -> dict:
    """Build and store today's summary drawer. Returns the metrics dict."""
    from yeti.memory.client import MemPalaceClient

    today = datetime.now(UTC)
    window_start = today - timedelta(days=1)
    metrics = collect_metrics(window_start)

    date_label = today.date().isoformat()
    body = render_summary(date_label, metrics)

    try:
        await MemPalaceClient().store(
            content=body,
            wing="meta",
            room="daily-summary",
            source=f"sleep-summary:{date_label}",
        )
    except Exception:
        logger.exception("Failed to store daily summary drawer")

    logger.info("Daily summary metrics: %s", metrics)
    return metrics
